unfoldingWord-dev/door43.org

.travis.yml
pages/en/contact.md
s3_dev_push.sh
s3_prod_push.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/62)

Verifying #1

---

pages/en/contact.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/64)

Clean up from testing

---

_sass/customize_theme.scss

unfoldingWord/unfoldingWord.github.io#171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/104)

Fix placement of menu on tablets

---

_sass/customize_theme.scss

unfoldingWord/unfoldingWord.github.io#172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/105)

Fixes a menu display problem in Safari and iOS

---

_layouts/reveal.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/106)

Issue #61: Add Google Analytics to all pages

---

_sass/customize_theme.scss
pages/en/contact.md

The other half of this task is in https://github.com/unfoldingWord-dev/slack-lambda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/107)

Issue 16: Slack signup page

---

pages/en/contact.md

Issue #16: Also prevent user from clicking on page while waiting for response from Lambda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/123)

Debugging Lambda problem

---

_layouts/obs.html
css/obs.scss
pages/templates/obs.md

Add files for generating the obs.html template
unfoldingWord-dev/door43.org#146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/149)

Issue 146: Implement design for OBS page

---

_layouts/bible.html
_layouts/obs.html
css/bible.scss
pages/templates/bible.md

Also renamed some items in the OBS template based on more complete information about what they represent in the mock-up.
unfoldingWord-dev/door43.org#152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/162)

Issue 152: Create the template for scripture

---

_layouts/bible.html
_layouts/obs.html
js/commit-page.js
js/general-tools.js

Just some changes for the commit pages so they display a bit better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/door43.org/187)

Update to commit page JS and status icons

---

js/commit-page.js
js/general-tools.js

Feature #213 solidify badge statuses
https://github.com/unfoldingWord-dev/door43.org/issues/213
Changes:
- replace fa fonts in badge status with specific pngs.

Feature #213 solidify badge statuses

---

pages/en/contact.md

Update Slack token

---

_layouts/bible.html
_layouts/obs.html
css/bible.scss
css/obs.scss
css/project-page.scss
js/project-page.js

For both Issues #189 and #190, OBS and Bible project page navigation.

Feature - Issues 189 and 190 - CSS and JS for project page navigation

---

s3_dev_push.sh

@richmahn will this do what you are looking for?

Fixed dev push to go to updated dev bucket

---

_layouts/bible.html
_layouts/obs.html
css/project-page.scss
js/project-page.js

See issue https://github.com/unfoldingWord-dev/door43.org/issues/326

Issue #326: Make header float

---

404.md

Feature 528 - update 404 page (#532)
* 404.md - updated text and added a go back anchor.

Merge develop into master

---

_layouts/bible.html
_layouts/obs.html
css/project-page.scss

Needed to style the Print button to be like in the mock up (https://github.com/unfoldingWord-dev/door43.org/issues/550#issuecomment-305519301)

Feature - Issue 550 - CSS for print button like in mock up

---

_layouts/bible.html
_layouts/obs.html

Fix for issue https://github.com/unfoldingWord-dev/door43.org/issues/71
Changes:
- Fix error in download button that opens new page rather than initiate download.

Feature 71 - Add Source Download Button

---

README.md
js/project-page-functions.js
karma.conf.js
karma_start_debug.sh
package.json
test/spec/SpecBadges.js
test/spec/SpecPageViews.js
test/spec/support/mock-ajax.js

Get page view count from API and display on screen.
Also cleaned up test/spec/SpecBadges.js to be more readable and improve coverage.

Feature 21/add page views

---

css/project-page.scss

Just some styling for tA project pages to make them more like the PDF styling.

Feature - Issue 573 - Updates the css to be the same as the PDF's css

---

js/i18n.js
test/spec/SpecI18N.js

Fixes on https://github.com/unfoldingWord-dev/door43.org/issues/579:
Have removed extra more button and search will fall back to default search if no search parameters.

Issue 579/default page load 2

---

README.md
karma.conf.js
package.json
run_karma_tests.sh
test/SpecRunner.html
test/spec/support/LoggingReporter.js

LoggingReporter.js - jasmine runtime configuration to send spec results to console.log().

Configuration changes to display and log Jasmine test results.

---

css/project-page.scss
js/project-page-functions.js
test/spec/SpecJsonProcessing.js
test/spec/SpecWarningModal.js

Feature requirements: https://github.com/unfoldingWord-dev/door43.org/issues/244
See here; http://test-door43.org.s3-website-us-west-2.amazonaws.com/u/richmahn/en-obs/8580a6d49f/
Lots of lines in modal: http://test-door43.org.s3-website-us-west-2.amazonaws.com/u/richmahn/en-obs/a1ea0fd171/

Feature - Issue #244 - Builds modal for warning messages on project page

---

_includes/i18n-footer.html
_layouts/i18n.html
js/application.js
js/general-tools.js
js/i18n.js
js/project-page-functions.js
run_karma_tests.sh
test/spec/SpecJsonProcessing.js
test/spec/SpecLanguageViews.js

Fix for Issue: https://github.com/unfoldingWord-dev/door43.org/issues/18
i18n.html & i18n.js - remove page views from language page

Fix_18/Remove page views from language page

---

_sass/customize_theme.scss

Issue: https://github.com/unfoldingWord-dev/door43.org/issues/66
fix pointer over logo - text pointer no longer shown.

Fix_66/Fix pointer shown over logo

---

pages/en/about/index.md
pages/en/about/new_door43.md

Added page about the new site

---

_layouts/project-page.html
js/project-page-functions.js

Not sure if I've got the right syntax @richmahn, please double check.

Added count for warn metrics

---

_plugins/pageless_redirects.rb
_redirects.yml

Added code for maintaining redirects

---

_includes/i18n-footer.html
js/i18n.js
test/spec/SpecManifestSearch.js
test/spec/SpecPopularRecentSections.js

Feature: https://github.com/unfoldingWord-dev/door43.org/issues/715
Replaced Dynamo DB access for search with call to lambda.

Feature 715/update client to use search lambda

---

js/project-page-functions.js
test/spec/SpecBuildInProcess.js

project-page-functions.js - checkConversionStatus() - fix to not refresh on conversion error.

Fix Project page to not refresh on conversion error.

---

js/project-page-functions.js
test/spec/SpecBuildInProcess.js

* project-page-functions.js - checkConversionStatus() - fix to not refresh on conversion error.
* checkConversionStatus() - fix to not refresh on conversion error.

Fix Project page to not refresh on conversion error. (#726)

---

js/application.js
test/spec/SpecLanguageViews.js

issue: https://github.com/unfoldingWord-dev/door43.org/issues/700
Update language 404 page search link to include resource if known.

Feature 700/Update language 404 page search link to include resource if known.

---

css/project-page.scss
js/jQuery.print.js
js/project-page-functions.js
test/spec/SpecJsonProcessing.js
test/spec/SpecWarningModal.js

Issue: https://github.com/unfoldingWord-dev/door43.org/issues/685 
Also raised warning label to look like button.
project-page-functions.js - showWarningModal() - modified to show print button.  Loads jquery.print.js on demand and shows print dialog.
Added jquery.print.js.

Feature 685/Print For WarningModal

---

_config.yml
_sass/customize_theme.scss
css/project-page.scss
js/i18n.js
js/jQuery.print.js
js/project-page-functions.js
test/spec/SpecBuildInProcess.js
test/spec/SpecJsonProcessing.js
test/spec/SpecWarningModal.js

* Fixes download button hard to use
* Adds print button to warning dialog
* Makes warning button look like a button with mouse hover

Updates and Fixes

---

css/project-page.scss

Needed for the PR in tx-manager for Issue #776

Fix - #776 - Added tQ to the project-page.scss file for navigation

---

js/project-page-functions.js
test/spec/SpecPrint.js

See https://github.com/unfoldingWord-dev/tx-manager/pull/201

Make js compatible with updated print API

---

README.md

Added a few extra set-up lines to the README that were required for set-up on my Ubuntu system.

Robh update

---

js/project-page-functions.js
test/spec/SpecJsonProcessing.js

Also removed "Show more" **functionality**

Second attempt at displaying Revisions better

---

js/project-page-functions.js

Was getting destroyed in the comparison

Try to retain the commit time

---

_layouts/project-page.html
css/project-page.scss
js/project-page-functions.js
test/spec/SpecJsonProcessing.js

Still don't really know what I'm doing (but haven't found a good way yet to test changes locally)

2nd attempt towards revising Revisions

---

js/project-page-functions.js
test/spec/SpecDcsLink.js
test/spec/SpecDownload.js
test/spec/SpecJsonProcessing.js
test/spec/SpecWarningModal.js

First attempt at allowing OBS PDF downloads

---

js/i18n.js
js/project-page-functions.js
pages/en/legal/copyright-violations.md
test/spec/SpecLanguageFilter.js

Filter out STR and tx-manager-test-data repos from most views.
(You can still search for those EXACT terms, though, i.e., using the full-text and correct case.).
Switch from Flask app at https://github.com/unfoldingWord-dev/dw-lang-switcher (accessed at https://us.door43.org:9096/?q=hi) to Django app at https://github.com/unfoldingWord-dev/translationDatabaseWeb (deployed on Heroku and accessed at https://td.unfoldingword.org/ac/langnames/?q=en for prodn or https://td-demo.unfoldingword.org/ac/langnames/?q=en for dev).

Add filters for usernames; change lg data supplier

---

package-lock.json
package.json

Rich updates
